# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lucifer_dex_dev_db

test:
  <<: *default
  database: lucifer_dex_test_db

production:
  <<: *default
  database: lucifer_dex_prod_db
